config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  get '/authorized' => 'sessions#page_requires_login'
  get '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get '/ingredient-list' => 'ingredients#list'

  resources :ingredients
  resources :reviews
  resources :users, except: [:edit, :update, :destroy] do
    resources :reviewed_recipes, only: [:index]
  end

  resources :recipes do
    resources :reviews, shallow: true
    resources :ingredients, only: [:index]
  end
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_many :reviews
    has_many :users, through: :reviews
    has_and_belongs_to_many :ingredients
    validates :name, :description, :date_created, presence: true

    scope :alphabetize, -> { order(:name) }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :find_recipe, only: [:show, :edit, :update, :destroy]

    def index
        @recipes = Recipe.all
    end

    def show
        @reviews = @recipe.reviews
    end

    def new
        @recipe = Recipe.new
        @ingredients = Ingredient.all
    end

    def create
        @recipe = current_user.recipes.build(recipe_params)
        
        if @recipe.save
            redirect_to recipe_path(@recipe)
        else
            flash.now[:messages] = @recipe.errors.full_messages
            render :new
        end
    end

    def edit
        unless current_user.id == @recipe.user_id
            redirect_to recipe_path(@recipe)
        end
    end

    def update
        if current_user.id == @recipe.user_id
            if @recipe.update(recipe_params)
                redirect_to recipe_path(@recipe)
            else
                render :edit
            end
        else
            redirect_to recipe_path(@recipe)
        end
    end

    def destroy
        @recipe.destroy
        redirect_to recipes_path
    end

    private

    def recipe_params
        params.require(:recipe).permit(:name, :description, :date_created, :user_id, :ingredient_ids, ingredient_ids: [])
    end

    def find_recipe
        @recipe = Recipe.find_by_id(params[:id])
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper

    def recipe_owner?(recipe)
        recipe.user == current_user
    end

end

app/views/recipes/_form.erb
<div class="fields_with_errors">

<% if flash[:messages] %>
    <% flash[:messages].each do |message| %>
        <%= message %> <br><br>
    <% end %>
<% end %>

</div>

<%= form_for(@recipe) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %> <br><br>

    <%= f.label :description %>
    <%= f.text_area :description %> <br><br>

    <%= f.label :date_created %>
    <%= f.date_select :date_created, :order => [:month, :day, :year] %> <br><br>

    <%= collection_check_boxes(:recipe, :ingredient_ids, Ingredient.all.alphabetize, :id, :name) do |box| %> 
        <%= box.check_box + box.text %>
    <% end %> <br><br>

    <%= f.submit %>

<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render 'form' %>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>

<ul>
<% @recipes.alphabetize.each do |recipe| %>
    <li><b><%= link_to recipe.name, recipe_path(recipe) %></b></li>
    <li>Posted on: <%= recipe.date_created.strftime("%B %-d, %Y") %></li>
    <li>Created by: <b><%= recipe.user.username %></b></li> <br><br>
<% end %>
</ul>


<%= link_to "New Recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe!!</h1>

<%= render 'form' %>

app/views/recipes/show.html.erb
<br>

<%= link_to "New Recipe", new_recipe_path %>


<h1><%= @recipe.name %></h1>

<p>Posted on: <%= @recipe.date_created.strftime("%B %-d, %Y") %> by <b><%= @recipe.user.username %></b></p>

<h3>Description: <%= @recipe.description %></h3>


<%= link_to "View All Ingredients", recipe_ingredients_path(@recipe) %> <br><br>

<%= link_to "Leave A Review", new_recipe_review_path(@recipe) %>

<br><br>

<% if recipe_owner?(@recipe) %>

<%= link_to "Edit Recipe", edit_recipe_path %>

<%= link_to "Delete Recipe", @recipe, method: "delete" %>

<% end %> <br>



<% if !!@reviews %>
<h3>Reviews:</h3>
<ul>

<% @reviews.each do |review| %>
    <li><%= review.user.username%> said:</li>
    <li><%= review.content %></li>
    <li><%= review.rating %> / 5</li> <br><br>
<% end %>
</ul>
<% end %>