config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  get '/authorized' => 'sessions#page_requires_login'
  get '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get '/ingredient-list' => 'ingredients#list'

  resources :ingredients
  resources :reviews
  resources :users, except: [:edit, :update, :destroy] do
    resources :reviewed_recipes, only: [:index]
  end

  resources :recipes do
    resources :reviews, shallow: true
    resources :ingredients, only: [:index]
  end
  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :recipes
    has_many :reviews
    has_many :reviewed_recipes, -> {distinct}, through: :reviews, source: :recipe
    has_secure_password
    validates :username, :email, presence: true
    validates :username, :email, uniqueness: true

    def self.create_from_omniauth(auth)
        User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
            u.username = auth['info']['first_name']
            u.email = auth['info']['email']
            u.password = SecureRandom.hex(12)
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    skip_before_action :authorized, only: [:new, :create]

    def index
    end

    def show
        @user = User.find_by_id(params[:id])
        @recipes = @user.recipes
    end

    def new
        @user = User.new
        render layout: false
    end

    def create
        @user = User.create(user_params)
    
        if @user.save
            session[:user_id] = @user.id
            redirect_to "/"
        else
            flash.now[:messages] = @user.errors.full_messages
            render :new
        end
    end

    # choosing to not let users update or delete their accounts, for now.

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>All Users</h1>

app/views/users/new.html.erb
<%= link_to "Home", "/" %>

<h1>Sign Up:</h1>

<div class="fields_with_errors">

<% if flash[:messages] %>
    <% flash[:messages].each do |message| %>
        <%= message %> <br><br>
    <% end %>
<% end %>

</div>

<%= form_for(@user) do |f| %>

    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Sign Up" %>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1>

<h3>Your Recipes:</h3>

<ul>
    <% @recipes.each do |recipe| %>
     <li><%= link_to recipe.name, recipe_path(recipe) %></li>
    <% end %>
</ul> <br>

<%= link_to "New Recipe", new_recipe_path %> <br><br><br>

<%= link_to "All Ingredients", '/ingredient-list' %> <br><br>

<%= link_to "My Reviewed Recipes", user_reviewed_recipes_path(@user) %> <br><br>

<%= link_to "New Ingredient", new_ingredient_path %>