config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  get '/authorized' => 'sessions#page_requires_login'
  get '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get '/ingredient-list' => 'ingredients#list'

  resources :ingredients
  resources :reviews
  resources :users, except: [:edit, :update, :destroy] do
    resources :reviewed_recipes, only: [:index]
  end

  resources :recipes do
    resources :reviews, shallow: true
    resources :ingredients, only: [:index]
  end
  
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_and_belongs_to_many :recipes
    validates :name, presence: true
    validates :name, uniqueness: true

    scope :alphabetize, -> { order(:name) }
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    before_action :find_ingredient, only: [:show, :edit, :update, :destroy]

    def index
        @recipe = Recipe.find_by_id(params[:recipe_id])
        if @recipe
            @ingredients = Ingredient.all
        else
            redirect_to recipes_path
        end
    end

    def show
    end

    def new
        @ingredient = Ingredient.new
    end

    def create
        @ingredient = Ingredient.new(ingredients_params)
        if @ingredient.save
            redirect_to new_recipe_path
        else

            render :new
        end
    end

    def edit
    end

    def update
        if @ingredient.update(ingredients_params)
            redirect_to ingredient_path(@ingredient)
        else
            render :edit
        end
    end

    def destroy
        @ingredient.destroy
        redirect_to ingredients_path
    end

    def list
        @ingredients = Ingredient.all
    end

    private

    def ingredients_params
        params.require(:ingredient).permit(:name, :amount)
    end

    def find_ingredient
        @ingredient = Ingredient.find_by_id(params[:id])
    end

end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %> <br><br>

    <%= f.submit %>

<% end %>

app/views/ingredients/edit.html.erb
<h1>Edit Ingredient</h1>

<%= render 'form' %>

app/views/ingredients/index.html.erb
<h1>Ingredients for <%= @recipe.name %></h1>

<ul>
<% @recipe.ingredients.each do |recipe| %>
    <li><%= recipe.name %></li>
<% end %>
</ul>

app/views/ingredients/list.html.erb
<h1>All Ingredients</h1>

<ul>
<% @ingredients.alphabetize.each do |ingredient| %>
    <li><b><%= link_to ingredient.name, ingredient_path(ingredient) %></b></li>
<% end %>
</ul>

<br>

<%= link_to "New Ingredient", new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form' %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name  %></h1>

<%= link_to "Edit Ingredient", edit_ingredient_path %> <br><br>

<%= link_to "Delete Ingredient", @ingredient, method: "delete" %>