config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  get '/authorized' => 'sessions#page_requires_login'
  get '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get '/ingredient-list' => 'ingredients#list'

  resources :ingredients
  resources :reviews
  resources :users, except: [:edit, :update, :destroy] do
    resources :reviewed_recipes, only: [:index]
  end

  resources :recipes do
    resources :reviews, shallow: true
    resources :ingredients, only: [:index]
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_recipe, only: [:new, :create]
    before_action :find_review, only: [:show, :edit, :update, :destroy]

    def index
        @reviews = Review.all
    end

    def show
    end

    def new
        @review = Review.new
    end

    def create
        @review = @recipe.reviews.build(reviews_params)
        @review.user = current_user
   
        if @review.save
            redirect_to recipe_path(@recipe)
        else
            flash.now[:messages] = @review.errors.full_messages
            render :new
        end
    end

    def edit
        unless current_user.id == @review.user_id
            redirect_to review_path(@review)
        end
    end

    def update
        if current_user.id == @review.user_id
            if @review.update(reviews_params)
                redirect_to review_path(@review)
            else
                render :edit
            end
        else
            redirect_to review_path(@review)
        end
    end

    def destroy
        @review.destroy
        redirect_to reviews_path
    end

    private

    def reviews_params
        params.require(:review).permit(:content, :rating)
    end

    def find_review
        @review = Review.find_by_id(params[:id])
    end

    def find_recipe
        @recipe = Recipe.find_by_id(params[:recipe_id])
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper

    def review_owner?(review)
        review.user == current_user
    end

end

app/views/reviews/_form.erb
<div class="fields_with_errors">

<% if flash[:messages] %>
    <% flash[:messages].each do |message| %>
        <%= message %> <br><br>
    <% end %>
<% end %>

</div>

<%= form_for [@recipe, @review] do |f| %>

    <%= f.label "Review:" %>
    <%= f.text_area :content %> <br><br>

    <%= f.label :rating %>
    <%= select_tag("review[rating]", options_for_select([1, 2, 3, 4, 5]))%> <br><br>

    <%= f.submit %>

<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review!!</h1>

<%= render 'form' %>

app/views/reviews/index.html.erb
<h1>All Reviews</h1>

<ul>
<% @reviews.each do |review| %>
    <li><%= review.content %></li>
    <li><%= review.rating %></li> <br><br>
<% end %>
</ul>

app/views/reviews/new.html.erb
<h1>New Review!!</h1>

<%= render 'form' %>

app/views/reviews/show.html.erb
<h1>Review</h1>

<%= @review.user.username %> said about <%= @review.recipe.name %>:<br><br>

<%= @review.content %>

<br><br>

<%= @review.rating %> / 5

 <br><br>

 <% if review_owner?(@review) %>

<%= link_to "Edit Review", edit_review_path %>

<%= link_to "Delete Review", @review, method: "delete" %>

<% end %> <br>